/// Integration tests for silero_vad_flutter.
///
/// These tests compare the Dart implementation against reference outputs
/// generated by the Python original implementation.
///
/// To run:
///   1. Generate reference data: python test/reference_generator.py model.onnx test.wav test/reference/
///   2. Run tests: flutter test
///
/// In CI, the workflow runs both steps automatically.
@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:silero_vad_flutter/silero_vad_flutter.dart';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Read a WAV file and return mono Float32List.
Float32List readWavFile(String path) {
  final file = File(path);
  final bytes = file.readAsBytesSync();
  final bd = ByteData.sublistView(bytes);

  // Verify RIFF header
  final riff = String.fromCharCodes(bytes.sublist(0, 4));
  if (riff != 'RIFF') throw FormatException('Not a WAV file: $path');

  // Parse chunks
  int pos = 12; // after RIFF header
  int sampleRate = 0;
  int numChannels = 0;
  int bitsPerSample = 0;
  Float32List? samples;

  while (pos < bytes.length - 8) {
    final chunkId = String.fromCharCodes(bytes.sublist(pos, pos + 4));
    final chunkSize = bd.getUint32(pos + 4, Endian.little);

    if (chunkId == 'fmt ') {
      numChannels = bd.getUint16(pos + 10, Endian.little);
      sampleRate = bd.getUint32(pos + 12, Endian.little);
      bitsPerSample = bd.getUint16(pos + 22, Endian.little);
    } else if (chunkId == 'data') {
      final dataStart = pos + 8;
      final numSamples = chunkSize ~/ (numChannels * (bitsPerSample ~/ 8));
      samples = Float32List(numChannels == 2 ? numSamples ~/ 2 : numSamples);

      if (bitsPerSample == 16) {
        int idx = 0;
        for (int i = 0; i < numSamples * numChannels; i += numChannels) {
          var sum = 0.0;
          for (int ch = 0; ch < numChannels; ch++) {
            final val = bd.getInt16(dataStart + (i + ch) * 2, Endian.little);
            sum += val / 32768.0;
          }
          samples[idx++] = numChannels == 2 ? sum / 2 : sum;
        }
      } else {
        throw UnsupportedError('Only 16-bit PCM supported');
      }
    }

    pos += 8 + chunkSize;
    if (chunkSize % 2 == 1) pos++; // padding
  }

  if (samples == null) throw FormatException('No data chunk found');
  return samples;
}

/// Read JSON file.
dynamic readJson(String path) {
  final file = File(path);
  if (!file.existsSync()) {
    throw StateError('Reference file not found: $path\n'
        'Run: python test/reference_generator.py <model.onnx> <test.wav> test/reference/');
  }
  return jsonDecode(file.readAsStringSync());
}

/// Compare two doubles with tolerance.
Matcher closeToDouble(double expected, {double tolerance = 1e-6}) {
  return predicate(
    (double actual) => (actual - expected).abs() < tolerance,
    'close to $expected within $tolerance',
  );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  // Paths - these are set by the CI workflow
  final modelPath = Platform.environment['TEST_MODEL_PATH']
      ?? '../src/silero_vad/data/silero_vad.onnx';
  final wavPath = Platform.environment['TEST_WAV_PATH']
      ?? '../../tests/data/test.wav';
  final refDir = Platform.environment['TEST_REF_DIR']
      ?? 'reference';

  // Resolve relative to test directory
  final testDir = Directory(Platform.script.path).parent.path;
  final resolvedModel = File(modelPath).existsSync()
      ? modelPath : '$testDir/$modelPath';
  final resolvedWav = File(wavPath).existsSync()
      ? wavPath : '$testDir/$wavPath';
  final resolvedRefDir = File(refDir).existsSync()
      ? refDir : '$testDir/$refDir';

  group('Silero VAD Flutter', () {
    late SileroVadModel model;
    late Float32List audio;

    setUpAll(() async {
      // Check files exist
      expect(File(resolvedModel).existsSync(), isTrue,
          reason: 'ONNX model not found: $resolvedModel');
      expect(File(resolvedWav).existsSync(), isTrue,
          reason: 'WAV file not found: $resolvedWav');

      model = await SileroVadModel.fromFile(resolvedModel);
      audio = readWavFile(resolvedWav);
    });

    tearDownAll(() {
      model.dispose();
    });

    // =====================================================================
    // Test 1: audioForward probabilities match reference
    // =====================================================================
    test('audioForward produces matching probabilities', () async {
      final refProbs = (readJson('$resolvedRefDir/probs.json') as List).cast<double>();

      final dartProbs = await model.audioForward(audio, 16000);

      expect(dartProbs.length, refProbs.length,
          reason: 'Probability count mismatch');

      double maxDiff = 0;
      int maxDiffIdx = 0;
      for (int i = 0; i < refProbs.length; i++) {
        final diff = (dartProbs[i] - refProbs[i]).abs();
        if (diff > maxDiff) {
          maxDiff = diff;
          maxDiffIdx = i;
        }
      }

      expect(maxDiff, closeToDouble(0.0, tolerance: 1e-6),
          reason: 'Max probability difference: $maxDiff at window $maxDiffIdx\n'
                  '  Ref: ${refProbs[maxDiffIdx]}\n'
                  '  Dart: ${dartProbs[maxDiffIdx]}');
    });

    // =====================================================================
    // Test 2: getSpeechTimestamps (samples) matches reference
    // =====================================================================
    test('getSpeechTimestamps (samples) matches reference', () async {
      final refTs = (readJson('$resolvedRefDir/timestamps.json') as List)
          .cast<Map<String, dynamic>>();

      final dartTs = await getSpeechTimestamps(audio, model,
          samplingRate: 16000, returnSeconds: false);

      expect(dartTs.length, refTs.length,
          reason: 'Segment count mismatch: Dart=${dartTs.length}, Ref=${refTs.length}');

      for (int i = 0; i < refTs.length; i++) {
        expect(dartTs[i].start, refTs[i]['start'],
            reason: 'Segment $i start mismatch');
        expect(dartTs[i].end, refTs[i]['end'],
            reason: 'Segment $i end mismatch');
      }
    });

    // =====================================================================
    // Test 3: getSpeechTimestamps (seconds) matches reference
    // =====================================================================
    test('getSpeechTimestamps (seconds) matches reference', () async {
      final refTs = (readJson('$resolvedRefDir/timestamps_seconds.json') as List)
          .cast<Map<String, dynamic>>();

      final dartTs = await getSpeechTimestamps(audio, model,
          samplingRate: 16000, returnSeconds: true);

      expect(dartTs.length, refTs.length,
          reason: 'Segment count mismatch');

      double maxDiff = 0;
      for (int i = 0; i < refTs.length; i++) {
        final startDiff = ((dartTs[i].start as double) - (refTs[i]['start'] as double)).abs();
        final endDiff = ((dartTs[i].end as double) - (refTs[i]['end'] as double)).abs();
        maxDiff = math.max(maxDiff, math.max(startDiff, endDiff));
      }

      expect(maxDiff, closeToDouble(0.0, tolerance: 1e-6),
          reason: 'Max timestamp difference in seconds: $maxDiff');
    });

    // =====================================================================
    // Test 4: VADIterator produces matching events
    // =====================================================================
    test('VADIterator produces matching events', () async {
      final refEvents = (readJson('$resolvedRefDir/vad_iterator.json') as List)
          .cast<Map<String, dynamic>>();

      final iterator = VADIterator(model, samplingRate: 16000);
      final dartEvents = <Map<String, dynamic>>[];

      const windowSize = 512;
      final numWindows = audio.length ~/ windowSize;
      for (int i = 0; i < numWindows; i++) {
        final window = Float32List(windowSize);
        window.setRange(0, windowSize, audio, i * windowSize);
        final result = await iterator.process(window);
        if (result != null) {
          if (result.containsKey('start')) {
            dartEvents.add({
              'window': i,
              'type': 'start',
              'pos': result['start'] as int,
            });
          } else if (result.containsKey('end')) {
            dartEvents.add({
              'window': i,
              'type': 'end',
              'pos': result['end'] as int,
            });
          }
        }
      }

      expect(dartEvents.length, refEvents.length,
          reason: 'Event count mismatch: Dart=${dartEvents.length}, Ref=${refEvents.length}');

      for (int i = 0; i < refEvents.length; i++) {
        expect(dartEvents[i]['window'], refEvents[i]['window'],
            reason: 'Event $i window mismatch');
        expect(dartEvents[i]['type'], refEvents[i]['type'],
            reason: 'Event $i type mismatch');
        expect(dartEvents[i]['pos'], refEvents[i]['pos'],
            reason: 'Event $i position mismatch');
      }
    });

    // =====================================================================
    // Test 5: collectChunks produces correct audio
    // =====================================================================
    test('collectChunks extracts correct audio', () async {
      final timestamps = await getSpeechTimestamps(audio, model,
          samplingRate: 16000, returnSeconds: false);

      final speechAudio = collectChunks(timestamps, audio);

      // Verify length
      var expectedLength = 0;
      for (final ts in timestamps) {
        expectedLength += (ts.end - ts.start).toInt();
      }
      expect(speechAudio.length, expectedLength);

      // Verify content
      var offset = 0;
      for (final ts in timestamps) {
        final len = (ts.end - ts.start).toInt();
        for (int j = 0; j < len; j++) {
          expect(speechAudio[offset + j], audio[ts.start.toInt() + j],
              reason: 'Audio mismatch at offset ${offset + j}');
        }
        offset += len;
      }
    });

    // =====================================================================
    // Test 6: dropChunks produces correct audio
    // =====================================================================
    test('dropChunks removes correct audio', () async {
      final timestamps = await getSpeechTimestamps(audio, model,
          samplingRate: 16000, returnSeconds: false);

      final nonSpeechAudio = dropChunks(timestamps, audio);

      // Verify total length
      final speechLen = timestamps.fold<int>(0, (sum, ts) => sum + (ts.end - ts.start).toInt());
      expect(nonSpeechAudio.length, audio.length - speechLen);
    });

    // =====================================================================
    // Test 7: readAudio/saveAudio roundtrip
    // =====================================================================
    test('WAV roundtrip preserves audio', () async {
      final tempDir = Directory.systemTemp.createTempSync('silero_vad_test');
      final outPath = '${tempDir.path}/roundtrip.wav';

      // Save a small chunk
      final chunk = Float32List(1600); // 100ms at 16kHz
      for (int i = 0; i < chunk.length; i++) {
        chunk[i] = math.sin(2 * math.pi * 440 * i / 16000).toFloat(); // 440Hz sine
      }

      await saveAudio(outPath, chunk, samplingRate: 16000);
      final readBack = await readAudio(outPath, samplingRate: 16000);

      expect(readBack.length, chunk.length,
          reason: 'Roundtrip length mismatch');

      double maxDiff = 0;
      for (int i = 0; i < chunk.length; i++) {
        final diff = (readBack[i] - chunk[i]).abs();
        if (diff > maxDiff) maxDiff = diff;
      }
      // PCM16 roundtrip has ~1/32768 precision
      expect(maxDiff, closeToDouble(0.0, tolerance: 1 / 16384.0),
          reason: 'WAV roundtrip max diff: $maxDiff');

      tempDir.deleteSync(recursive: true);
    });
  });
}
